### ISSUE TITLE
【问题】浏览器拉到底部时重复自动刷新

### ISSUE THREAD

**Issue by Plalyy** [bear-zd/shuggle#1]
google chrome 和 edge 打开网页拉动到最底部时，网站不断刷新

**Comment by bear-zd** [comment]
这可能是由js引起的，在文章数量较多的情况下，向下滚动会自动加载更多文章从而使得页面更新，由于目前页面文章数量不足，无法加载更多文章，且每次到达底部加载之后会等待一段时间才会重新跳到底部，因此看上去可能像是不断刷新。

**Comment by bear-zd** [comment]
这可能是由js引起的，在文章数量较多的情况下，向下滚动会自动加载更多文章从而使得页面更新，由于目前页面文章数量不足，无法加载更多文章，且每次到达底部加载之后会等待一段时间才会重新跳到底部，因此看上去可能像是不断刷新。
